spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


club.dlblog:
 socketio:
  host: localhost
  port: 9000
 ueditor:
  baseUrl: http://localhost:8080/file/
  savePath: var/editor/file/
# log level
logging.level:
  root: WARN
  org.springframework: DEBUG
  org.apache.coyote.http11.Http11InputBuffer: DEBUG
  club.dlblog: DEBUG
  sample.mybatis.mapper: DEBUG
  org.apache.ibatis: DEBUG